name: Run Node.js Bot

on:
  push:
    branches:
      - main  # Change this to the appropriate branch name

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Change this to your preferred Node.js version

      - name: Install dependencies
        run: |
          npm install telegraf axios fs nodemon

      - name: Run bot script
        run: node bot.js
